### ISSUE TITLE
Collect Study Portals data

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/eis#3]
Collect data about Computer Science from the Study Portals project site.

**Comment by jaklinger** [comment]
I found a way to reverse engineer the website and get every course (bachelors, phd, master, preparation and short = 170k courses) by discipline and subdiscipline e.g. 

`Computer Science & IT` --> `Artificial Intelligence`

the data will come back in a very structured way (description, geography, course duration, face2face vs online)

I think it would take around 2 hours for the data collect on a single machine, and will likely be less than 1GB of data, so I can prototype the whole thing locally, and probably one day to write the data collection code. 

I'll perform the pilot here, and then integrate into DAPS in a second phase, since this will be very interesting to @djyldyz and others
